export interface ISOScript {
  code: string;
  name: string;
  common?: boolean;
}

// Source: https://www.unicode.org/iso15924/iso15924-codes.html
export const ISO_15924_SCRIPTS: ISOScript[] = [
  // Frequently Used Scripts
  { code: "Latn", name: "Latin", common: true },
  { code: "Arab", name: "Arabic", common: true },
  { code: "Cyrl", name: "Cyrillic", common: true },
  { code: "Deva", name: "Devanagari", common: true },
  { code: "Grek", name: "Greek", common: true },
  { code: "Hebr", name: "Hebrew", common: true },
  { code: "Hans", name: "Han (Simplified variant)", common: true },
  { code: "Hant", name: "Han (Traditional variant)", common: true },
  { code: "Hani", name: "Han (Hanzi, Kanji, Hanja)", common: true },
  { code: "Jpan", name: "Japanese (Han + Hiragana + Katakana)", common: true },
  { code: "Kore", name: "Korean (Hangul + Han)", common: true },
  { code: "Hang", name: "Hangul", common: true },
  { code: "Hira", name: "Hiragana", common: true },
  { code: "Kana", name: "Katakana", common: true },
  { code: "Thai", name: "Thai", common: true },
  { code: "Beng", name: "Bengali (Bangla)", common: true },
  { code: "Taml", name: "Tamil", common: true },
  { code: "Telu", name: "Telugu", common: true },
  { code: "Mlym", name: "Malayalam", common: true },
  { code: "Gujr", name: "Gujarati", common: true },
  { code: "Knda", name: "Kannada", common: true },
  { code: "Gurm", name: "Gurmukhi", common: true },
  { code: "Orya", name: "Oriya (Odia)", common: true },
  { code: "Sinh", name: "Sinhala", common: true },
  { code: "Khmr", name: "Khmer", common: true },
  { code: "Laoo", name: "Lao", common: true },
  { code: "Mymr", name: "Myanmar (Burmese)", common: true },
  { code: "Geor", name: "Georgian (Mkhedruli)", common: true },
  { code: "Armn", name: "Armenian", common: true },
  { code: "Ethi", name: "Ethiopic (Geʻez)", common: true },

  // Additional Active & Historical Scripts
  { code: "Adlm", name: "Adlam" },
  { code: "Afak", name: "Afaka" },
  { code: "Aghb", name: "Caucasian Albanian" },
  { code: "Ahom", name: "Ahom" },
  { code: "Armi", name: "Imperial Aramaic" },
  { code: "Avst", name: "Avestan" },
  { code: "Bali", name: "Balinese" },
  { code: "Bamu", name: "Bamum" },
  { code: "Bass", name: "Bassa Vah" },
  { code: "Batk", name: "Batak" },
  { code: "Bhks", name: "Bhaiksuki" },
  { code: "Bopo", name: "Bopomofo" },
  { code: "Brah", name: "Brahmi" },
  { code: "Brai", name: "Braille" },
  { code: "Bugi", name: "Buginese" },
  { code: "Buhd", name: "Buhid" },
  { code: "Cakm", name: "Chakma" },
  { code: "Cans", name: "Unified Canadian Aboriginal Syllabics" },
  { code: "Cari", name: "Carian" },
  { code: "Cham", name: "Cham" },
  { code: "Cher", name: "Cherokee" },
  { code: "Chrs", name: "Chorasmian" },
  { code: "Copt", name: "Coptic" },
  { code: "Cpmn", name: "Cypro-Minoan" },
  { code: "Cprt", name: "Cypriot syllabary" },
  { code: "Diak", name: "Dives Akuru" },
  { code: "Dogr", name: "Dogra" },
  { code: "Dsrt", name: "Deseret (Mormon)" },
  { code: "Dupl", name: "Duployan shorthand" },
  { code: "Egyp", name: "Egyptian hieroglyphs" },
  { code: "Elba", name: "Elbasan" },
  { code: "Elym", name: "Elymaic" },
  { code: "Gagk", name: "Gagauz" },
  { code: "Glag", name: "Glagolitic" },
  { code: "Gong", name: "Gunjala Gondi" },
  { code: "Gonm", name: "Masaram Gondi" },
  { code: "Goth", name: "Gothic" },
  { code: "Gran", name: "Grantha" },
  { code: "Hatr", name: "Hatran" },
  { code: "Hluw", name: "Anatolian Hieroglyphs" },
  { code: "Hmng", name: "Pahawh Hmong" },
  { code: "Hmnp", name: "Nyiakeng Puachue Hmong" },
  { code: "Hung", name: "Old Hungarian" },
  { code: "Ital", name: "Old Italic" },
  { code: "Java", name: "Javanese" },
  { code: "Kali", name: "Kayah Li" },
  { code: "Khar", name: "Kharoshthi" },
  { code: "Kits", name: "Khitan small script" },
  { code: "Kpel", name: "Kpelle" },
  { code: "Kthi", name: "Kaithi" },
  { code: "Lana", name: "Tai Tham (Lanna)" },
  { code: "Latf", name: "Latin (Fraktur variant)" },
  { code: "Latg", name: "Latin (Gaelic variant)" },
  { code: "Leke", name: "Leke" },
  { code: "Lepc", name: "Lepcha (Róng)" },
  { code: "Limb", name: "Limbu" },
  { code: "Lina", name: "Linear A" },
  { code: "Linb", name: "Linear B" },
  { code: "Lisu", name: "Lisu (Fraser)" },
  { code: "Loma", name: "Loma" },
  { code: "Lyci", name: "Lycian" },
  { code: "Lydi", name: "Lydian" },
  { code: "Mahj", name: "Mahajani" },
  { code: "Maka", name: "Makasar" },
  { code: "Mand", name: "Mandaic" },
  { code: "Mani", name: "Manichaean" },
  { code: "Marc", name: "Marchen" },
  { code: "Medf", name: "Medefaidrin" },
  { code: "Mend", name: "Mende Kikakui" },
  { code: "Merc", name: "Meroitic Cursive" },
  { code: "Mero", name: "Meroitic Hieroglyphic" },
  { code: "Modi", name: "Modi" },
  { code: "Mong", name: "Mongolian" },
  { code: "Mroo", name: "Mro" },
  { code: "Mtei", name: "Meitei Mayek" },
  { code: "Mult", name: "Multani" },
  { code: "Nand", name: "Nandinagari" },
  { code: "Narb", name: "Old North Arabian" },
  { code: "Nbat", name: "Nabataean" },
  { code: "Newa", name: "Newa (Newar)" },
  { code: "Nkoo", name: "N'Ko" },
  { code: "Nshu", name: "Nüshu" },
  { code: "Ogam", name: "Ogham" },
  { code: "Olck", name: "Ol Chiki (Santali)" },
  { code: "Orkh", name: "Old Turkic (Orkhon Runic)" },
  { code: "Osge", name: "Osage" },
  { code: "Osma", name: "Osmanya" },
  { code: "Ougr", name: "Old Uyghur" },
  { code: "Palm", name: "Palmyrene" },
  { code: "Pauh", name: "Pau Cin Hau" },
  { code: "Perm", name: "Old Permic" },
  { code: "Phag", name: "Phags-pa" },
  { code: "Phli", name: "Inscriptional Pahlavi" },
  { code: "Phlp", name: "Psalter Pahlavi" },
  { code: "Phnx", name: "Phoenician" },
  { code: "Plrd", name: "Miao (Pollard)" },
  { code: "Prti", name: "Inscriptional Parthian" },
  { code: "Rjng", name: "Rejang" },
  { code: "Rohg", name: "Hanifi Rohingya" },
  { code: "Runr", name: "Runic" },
  { code: "Samr", name: "Samaritan" },
  { code: "Sarb", name: "Old South Arabian" },
  { code: "Saur", name: "Saurashtra" },
  { code: "Sgnw", name: "SignWriting" },
  { code: "Shaw", name: "Shavian" },
  { code: "Shrd", name: "Sharada" },
  { code: "Sidd", name: "Siddham" },
  { code: "Sind", name: "Khudawadi (Sindhi)" },
  { code: "Sogd", name: "Sogdian" },
  { code: "Sogo", name: "Old Sogdian" },
  { code: "Sora", name: "Sora Sompeng" },
  { code: "Soyo", name: "Soyombo" },
  { code: "Sund", name: "Sundanese" },
  { code: "Sylo", name: "Syloti Nagri" },
  { code: "Syrc", name: "Syriac" },
  { code: "Tagb", name: "Tagbanwa" },
  { code: "Takr", name: "Takri" },
  { code: "Tale", name: "Tai Le" },
  { code: "Talu", name: "New Tai Lue" },
  { code: "Tang", name: "Tangut" },
  { code: "Tavt", name: "Tai Viet" },
  { code: "Tibt", name: "Tibetan" },
  { code: "Tirh", name: "Tirhuta" },
  { code: "Tnsa", name: "Tangsa" },
  { code: "Toto", name: "Toto" },
  { code: "Ugar", name: "Ugaritic" },
  { code: "Vaii", name: "Vai" },
  { code: "Vith", name: "Vithkuqi" },
  { code: "Wara", name: "Warang Citi" },
  { code: "Wcho", name: "Wancho" },
  { code: "Xpeo", name: "Old Persian Cuneiform" },
  { code: "Xsux", name: "Sumero-Akkadian Cuneiform" },
  { code: "Yezi", name: "Yezidi" },
  { code: "Yiii", name: "Yi" },
  { code: "Zanb", name: "Zanabazar Square" },
  { code: "Zyyy", name: "Undetermined script" },
  { code: "Zzzz", name: "Uncoded script" },
];

export function filterScripts(query: string): ISOScript[] {
  const q = query.trim().toLowerCase();
  if (!q) return ISO_15924_SCRIPTS;

  return ISO_15924_SCRIPTS.filter(
    (item) =>
      item.code.toLowerCase().includes(q) ||
      item.name.toLowerCase().includes(q),
  );
}

export function getScriptInfo(code: string): ISOScript | undefined {
  return ISO_15924_SCRIPTS.find(
    (s) => s.code.toLowerCase() === code.trim().toLowerCase(),
  );
}
